### PR TITLE
Fix table overlap

### LINKED ISSUE #84: table overlaps text
### Summary

table overlaps text on  some pages. See Contributing to Ansible-maintained Collections page,  screenshot below.

Screenshot 2023-02-03 at 3 08 33 PM

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes #84.

### CODE REVIEW

**Comment by felixfontein** [comment]
@webknjaz @ssbarnea is there a chance to get this eventually merged and released?

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
@felixfontein I also added you to the repository, it might prove useful in the future, especially as devtools team no longer uses sphinx. And btw, thanks!

**Comment by felixfontein** [comment]
@ssbarnea thanks! Can you also add @oraNod, since this is used for the ansible-core and Ansible docsites?

**Comment by oraNod** [comment]
@felixfontein Thanks! And thanks to you too, @ssbarnea

**Pull request merged**
