### PR TITLE
Use antsibull extension instead of vendoring its content

### PR DESCRIPTION
**Pull request by felixfontein**
The "correct' source for the ansible-output lexer and the antsibull CSS is the `sphinx_antsibull_ext` antsibull Sphinx extension. So let's use it instead of replicating its conents :)

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
I agree that it's nice to have a single canonical upstream for the lexer. But I'm against making antsibull a dependency of this theme because it's extremely heavy on the deps it brings.

antsibull is an app, not a library. As such, it may come with stricter and unnecessary transitive deps that don't belong in a sphinx building env. Besides, it brings more implicit deps pinning that a sphinx theme should impose.

The lexer itself needs exactly zero of those deps except for an implicit dependency on Sphinx itself in one place. I don't want the users of the theme to pull in half of the async ecosystem just because it's unnecessarily present in some transitive metadata.

The theme shall remain as lightweight as possible. This is why I'm planning on applying a Sphinx 4 compat fix in this project for now.

But if the lexer (and possibly the related pygments style) end up packaged separately without all those deps, I'll be glad to reconsider making that a dependency.

**Comment by webknjaz** [comment]
There's now a lot of conflicts here and we still need to agree on how to handle the extension elsewhere. Thus I'm closing this PR and let's open a new one once all the things have been sorted.

**Comment by webknjaz** [comment]
@felixfontein could you re-send the CSS portion of this PR?

**Comment by felixfontein** [comment]
I was about to, but then I noticed https://github.com/ansible/ansible/blob/devel/docs/templates/collections_galaxy_meta.rst.j2. I'm currently re-evaluating which parts of the CSS should really be removed (it's probably a very small amount).

**Comment by felixfontein** [comment]
See #34.

**Pull request closed without merging**
